name: Release

on:
  push:
    tags:
    - "v*.*.*"

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build for all platforms
      run: make release-all

    - name: Generate checksum
      run: cd _out && sha256sum *.tar.gz > sha256sum.txt

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: |
          _out/*.tar.gz
          _out/sha256sum.txt
